---
# Docker provides a quick and automated way to install using a script
# But we are gonna do it manually just for testing and practice purposes
- name: Install docker
  hosts: localhost
  become: yes
  tasks:
    - block:
        - name: Enable EPEL repository and install yum-utils package
          ansible.builtin.yum:
            name:
              - epel-release
              - yum-utils
        - name: Add docker repository
          ansible.builtin.yum_repository:
            name: docker
            description: Docker YUM repo
            baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        - name: Uninstall old versions of docker
          ansible.builtin.yum:
            name:
              - docker
              - docker-client
              - docker-client-latest
              - docker-common
              - docker-latest
              - docker-latest-logrotate
              - docker-logrotate
              - docker-engine
            state: absent
        - name: Install docker engine
          ansible.builtin.yum:
            name: 
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
        - name: Start docker, if not started
          ansible.builtin.service:
            name: docker
            state: started
        - name: Test docker
          ansible.builtin.command: docker run hello-world
          register: result
        - name: Print test result
          ansible.builtin.debug:
            var: result.stdout
      when: ansible_distribution == "CentOS"
                

