---
- name: Git setup
  hosts: all
  # Need privilege escalation to create folder in /var/
  become: yes
  tasks:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present
    - name: Clone remote repository
      ansible.builtin.git:
        repo: 'https://github.com/hristijankocev/mcil'
        dest: "{{ web_app_local_repo_path }}"
        update: no  
